### PR TITLE
fix: stardict qstring modification

### LINKED ISSUE #1702: crash when make full-text index on certain stardict dictionaries.
Condition:
enable stardict dictionay full-text 

During the full-text indexing process,  the gd-ng will crash.

Analysis result:
[a.txt](https://github.com/user-attachments/files/16318021/a.txt)

The dictionary:
https://github.com/digitalpalidictionary/digitalpalidictionary/releases/tag/v0.1.20240522

### PR DESCRIPTION
**Pull request by xiaoyifang**
the stardict qstring part has caused crash sometimes.
Fix #1702

basic rule: avoid unnecessary conversions between QString and string 

Changes:
1.
```
QString newTag   = QString::fromUtf8(
            ( addAudioLink( href, getId() ) + "<span class=\"sdict_h_wav\"><a href=" + href + ">" ).c_str() );
```
to 
string only.

2. `return (articleText.toUtf8.data());`
to
```
     auto text = articleText.toUtf8();
      return text.data();
```

3. 
`QString stripHtml( const QString & tmp )`
to
`QString stripHtml( QString tmp )`

### CODE REVIEW

File: src/dict/stardict.cc [hunk 1]
```diff
@@ -525,29 +525,28 @@ string StardictDictionary::handleResource( char type, char const * resource, siz
...
       if ( pos ) {
         articleNewText += articleText.mid( pos );
         articleText = articleNewText;
         articleNewText.clear();
       }
-
-      return articleText.toStdString();
+      auto text = articleText.toUtf8();
+      return text.data();
     }
```
Comment (shenlebantongying) [inline src/dict/stardict.cc:550]: How can this fix anything?

There isn't much difference.
* in the new code, `std::string(toUtf8().data()) `will seek for the null byte again 
* in the old code, toStdString's `std::string(toUtf8().data(),toUtf8().size())` will use a articleText's actual length

Should a comment be added states that article Text may contain null byte, and we want cuf off earlier?

Comment (xiaoyifang) [reply src/dict/stardict.cc:550]: the original code is 
`return (articleText.toUtf8().data());`
I guess `articleText.toUtf8()` will generate a temporary string .  when chained with  `.data()`  .   sometimes the temporary variable has no longer existed.

Comment (xiaoyifang) [reply src/dict/stardict.cc:550]: > * in the old code, toStdString's `std::string(toUtf8().data(),toUtf8().size())` will use the articleText's actual length

the old code is `return (articleText.toUtf8.data());`  ,`toStdString()` is my first attempt.

Comment (xiaoyifang) [reply src/dict/stardict.cc:550]: https://bugreports.qt.io/browse/QTBUG-63274

Comment (xiaoyifang) [reply src/dict/stardict.cc:550]: Any relation?
image

https://doc.qt.io/qt-6/qstring.html#details:~:text=Note%3A%20Due,for%20more%20information.

Comment (shenlebantongying) [reply src/dict/stardict.cc:550]: If a temporal toStdString at return position would crash, then there are various other places would also crash already, so I don't think this is the root problem.

:sweat_smile: I have no other ideas as of now.

Comment (shenlebantongying) [reply src/dict/stardict.cc:550]: > Any relation?

I don't think so. That section of doc only says iterator or "pointer to the data of QString" may become invalidate.

But we don't use any of them here.

Comment (xiaoyifang) [reply src/dict/stardict.cc:550]: I also can not be sure.

But Qt+MSVC  QString   are more likely to have issue as the https://bugreports.qt.io/browse/QTBUG-63274 implies

**Comment by xiaoyifang** [comment]
Good news is that ,with the fix, the crash has gone. really misterious.

**Comment by shenlebantongying** [comment]
The changes look fine. For merging this, I don't think we need to know the root cause, which may reveal in the future.

Old & new code should be equivalent if things work as they are documented/written anyway :sweat_smile:.

File: src/dict/stardict.cc (hunk 1 above)
Comment (shenlebantongying) [reply src/dict/stardict.cc:550]: This seems to be the correct way to set /MD /MT
```
set_property(TARGET foo PROPERTY
  MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
```
https://github.com/qt/qtbase/blob/02cb165ef8050230b477358e4136e9f0acd83eb6/cmake/QtPublicTargetHelpers.cmake#L395-L397

However, CMake's doc says 

> If the property is not set, then CMake uses the default value MultiThreaded$<$<CONFIG:Debug>:Debug>DLL to select a MSVC runtime library.

So, I suppose it is set correctly by CMake already.

https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html

Comment (xiaoyifang) [reply src/dict/stardict.cc:550]: should cmake_policy be set?
https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html#:~:text=Note%20This%20property%20has%20effect%20only%20when%20policy%20CMP0091%20is%20set%20to%20NEW%20prior%20to%20the%20first%20project()%20or%20enable_language()%20command%20that%20enables%20a%20language%20using%20a%20compiler%20targeting%20the%20MSVC%20ABI.

Comment (shenlebantongying) [reply src/dict/stardict.cc:550]: No,`cmake_minimum_required` will set policy version, and we currently set it aggressively high :sweat_smile:.

https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html#policy-settings

https://github.com/xiaoyifang/goldendict-ng/blob/3ef35daec3fa7be0597255102e5db2288023e809/CMakeLists.txt#L1

Comment (shenlebantongying) [reply src/dict/stardict.cc:550]: I think search in the `build.ninja` file in the build folder to confirm /MD /MT is set.
