### PR TITLE
revert: tiff2imag method ,part of commit 5d9b930de5472e933d5260837569…

### LINKED ISSUE #2202: The last two versions of MacOS have frequently reported errors.
**描述 bug**

随机操作报错闪退。没有规律。

**系统和软件的版本**

MacOS 15.3.1

报错信息：

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               GoldenDict-ng [81101]
Path:                  /Applications/GoldenDict-ng.app/Contents/MacOS/GoldenDict-ng
Identifier:            org.xiaoyifang
Version:               25.04.0 (???)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2025-02-26 15:51:53.1648 +0800
OS Version:            macOS 15.3.1 (24D70)
Report Version:        12
Anonymous UUID:        ACE98172-167E-A198-0C40-13044CC98919

Sleep/Wake UUID:       BE7D1D77-063F-4CF0-B314-7159DA55F027

Time Awake Since Boot: 200000 seconds
Time Since Wake:       32191 seconds

System Integrity Protection: enabled

Crashed Thread:        36  Thread (pooled)

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000001ef7dbffe
Exception Codes:       0x0000000000000001, 0x00000001ef7dbffe

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [81101]

VM Region Info: 0x1ef7dbffe is not in any region.  Bytes after previous region: 33554431  Bytes before following region: 2
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      unused __TEXT               1ed7d84e0-1ed7dc000    [   15K] r--/rw- SM=COW  unused  unknown system shared lib __TEXT
--->  GAP OF 0x2000000 BYTES
      __DATA                      1ef7dc000-1ef7df5c0    [   13K] rw-/rw- SM=COW  /usr/lib/libobjc.A.dylib

Thread 0:: CrBrowserMain Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x188286f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x188299604 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18828faf8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x18828729c mach_msg + 24
4   CoreFoundation                	       0x1883b0a4c __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1883af2ac __CFRunLoopRun + 1212
6   CoreFoundation                	       0x1883ae734 CFRunLoopRunSpecific + 588
7   HIToolbox                     	       0x19391d530 RunCurrentEventLoopInMode + 292
8   HIToolbox                     	       0x193923348 ReceiveNextEventCommon + 676
9   HIToolbox                     	       0x193923508 _BlockUntilNextEventMatchingListInModeWithFilter + 76
10  AppKit                        	       0x18bf26848 _DPSNextEvent + 660
11  AppKit                        	       0x18c88cc24 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
12  AppKit                        	       0x18bf19874 -[NSApplication run] + 480
13  libqcocoa.dylib               	       0x107575f40 0x107560000 + 89920
14  QtCore                        	       0x107fddabc QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 540
15  QtCore                        	       0x107fd45b8 QCoreApplication::exec() + 112
16  GoldenDict-ng                 	       0x10483de68 main + 5216
17  dyld                          	       0x187f48274 start + 2840

Thread 1:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	       0x188291fbc __select + 8
1   CoreFoundation                	       0x1883d7638 __CFSocketManager + 704
2   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
3   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 2:: caulk.messenger.shared:17
0   libsystem_kernel.dylib        	       0x188286ed0 semaphore_wait_trap + 8
1   caulk                         	       0x1933f3ff4 caulk::semaphore::timed_wait(double) + 220
2   caulk                         	       0x1933f3ea0 caulk::concurrent::details::worker_thread::run() + 36
3   caulk                         	       0x1933f3b74 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 96
4   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
5   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 3:: caulk.messenger.shared:high
0   libsystem_kernel.dylib        	       0x188286ed0 semaphore_wait_trap + 8
1   caulk                         	       0x1933f3ff4 caulk::semaphore::timed_wait(double) + 220
2   caulk                         	       0x1933f3ea0 caulk::concurrent::details::worker_thread::run() + 36
3   caulk                         	       0x1933f3b74 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 96
4   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
5   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 4:: ThreadPoolServiceThread
0   libsystem_kernel.dylib        	       0x188292cfc kevent64 + 8
1   QtWebEngineCore               	       0x12059adb4 0x11c1c4000 + 71134644
2   QtWebEngineCore               	       0x12059abac 0x11c1c4000 + 71134124
3   QtWebEngineCore               	       0x12053e078 0x11c1c4000 + 70754424
4   QtWebEngineCore               	       0x1204fd5d0 0x11c1c4000 + 70489552
5   QtWebEngineCore               	       0x120560d64 0x11c1c4000 + 70896996
6   QtWebEngineCore               	       0x12054981c 0x11c1c4000 + 70801436
7   QtWebEngineCore               	       0x120560ee0 0x11c1c4000 + 70897376
8   QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
9   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
10  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 5:: ThreadPoolForegroundWorker
0   libsystem_kernel.dylib        	       0x188286f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x188299604 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18828faf8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x18828729c mach_msg + 24
4   QtWebEngineCore               	       0x1205949f4 0x11c1c4000 + 71109108
5   QtWebEngineCore               	       0x12051db64 0x11c1c4000 + 70622052
6   QtWebEngineCore               	       0x1205544d0 0x11c1c4000 + 70845648
7   QtWebEngineCore               	       0x12055526c 0x11c1c4000 + 70849132
8   QtWebEngineCore               	       0x120554ba8 0x11c1c4000 + 70847400
9   QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
10  libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
11  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 6:: ThreadPoolBackgroundWorker
0   libsystem_kernel.dylib        	       0x188286f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x188299604 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18828faf8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x18828729c mach_msg + 24
4   QtWebEngineCore               	       0x1205949f4 0x11c1c4000 + 71109108
5   QtWebEngineCore               	       0x12051db64 0x11c1c4000 + 70622052
6   QtWebEngineCore               	       0x1205544d0 0x11c1c4000 + 70845648
7   QtWebEngineCore               	       0x12055526c 0x11c1c4000 + 70849132
8   QtWebEngineCore               	       0x120554bdc 0x11c1c4000 + 70847452
9   QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
10  libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
11  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 7:: Chrome_IOThread
0   libsystem_kernel.dylib        	       0x188292cfc kevent64 + 8
1   QtWebEngineCore               	       0x12059adb4 0x11c1c4000 + 71134644
2   QtWebEngineCore               	       0x12059abac 0x11c1c4000 + 71134124
3   QtWebEngineCore               	       0x12053e078 0x11c1c4000 + 70754424
4   QtWebEngineCore               	       0x1204fd5d0 0x11c1c4000 + 70489552
5   QtWebEngineCore               	       0x120560d64 0x11c1c4000 + 70896996
6   QtWebEngineCore               	       0x11ecfd9fc 0x11c1c4000 + 45324796
7   QtWebEngineCore               	       0x120560ee0 0x11c1c4000 + 70897376
8   QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
9   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
10  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 8:: NetworkConfigWatcher
0   libsystem_kernel.dylib        	       0x188286f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x188299604 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18828faf8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x18828729c mach_msg + 24
4   QtWebEngineCore               	       0x1205949f4 0x11c1c4000 + 71109108
5   QtWebEngineCore               	       0x12051db64 0x11c1c4000 + 70622052
6   QtWebEngineCore               	       0x12051dae0 0x11c1c4000 + 70621920
7   QtWebEngineCore               	       0x1204cc584 0x11c1c4000 + 70288772
8   QtWebEngineCore               	       0x12053e078 0x11c1c4000 + 70754424
9   QtWebEngineCore               	       0x1204fd5d0 0x11c1c4000 + 70489552
10  QtWebEngineCore               	       0x120560d64 0x11c1c4000 + 70896996
11  QtWebEngineCore               	       0x120560ee0 0x11c1c4000 + 70897376
12  QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
13  libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
14  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 9:: ThreadPoolForegroundWorker
0   libsystem_kernel.dylib        	       0x188286f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x188299604 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18828faf8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x18828729c mach_msg + 24
4   QtWebEngineCore               	       0x1205949f4 0x11c1c4000 + 71109108
5   QtWebEngineCore               	       0x12051db64 0x11c1c4000 + 70622052
6   QtWebEngineCore               	       0x1205544d0 0x11c1c4000 + 70845648
7   QtWebEngineCore               	       0x12055526c 0x11c1c4000 + 70849132
8   QtWebEngineCore               	       0x120554ba8 0x11c1c4000 + 70847400
9   QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
10  libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
11  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 10:: ThreadPoolForegroundWorker
0   libsystem_kernel.dylib        	       0x188286f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x188299604 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18828faf8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x18828729c mach_msg + 24
4   QtWebEngineCore               	       0x1205949f4 0x11c1c4000 + 71109108
5   QtWebEngineCore               	       0x12051db64 0x11c1c4000 + 70622052
6   QtWebEngineCore               	       0x1205544d0 0x11c1c4000 + 70845648
7   QtWebEngineCore               	       0x12055526c 0x11c1c4000 + 70849132
8   QtWebEngineCore               	       0x120554ba8 0x11c1c4000 + 70847400
9   QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
10  libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
11  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 11:: Chrome_InProcGpuThread
0   libsystem_kernel.dylib        	       0x188286f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x188299604 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18828faf8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x18828729c mach_msg + 24
4   QtWebEngineCore               	       0x1205949f4 0x11c1c4000 + 71109108
5   QtWebEngineCore               	       0x12051db64 0x11c1c4000 + 70622052
6   QtWebEngineCore               	       0x1204cc520 0x11c1c4000 + 70288672
7   QtWebEngineCore               	       0x12053e078 0x11c1c4000 + 70754424
8   QtWebEngineCore               	       0x1204fd5d0 0x11c1c4000 + 70489552
9   QtWebEngineCore               	       0x120560d64 0x11c1c4000 + 70896996
10  QtWebEngineCore               	       0x120560ee0 0x11c1c4000 + 70897376
11  QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
12  libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
13  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 12:: Chrome_ChildIOThread
0   libsystem_kernel.dylib        	       0x188292cfc kevent64 + 8
1   QtWebEngineCore               	       0x12059adb4 0x11c1c4000 + 71134644
2   QtWebEngineCore               	       0x12059abac 0x11c1c4000 + 71134124
3   QtWebEngineCore               	       0x12053e078 0x11c1c4000 + 70754424
4   QtWebEngineCore               	       0x1204fd5d0 0x11c1c4000 + 70489552
5   QtWebEngineCore               	       0x120560d64 0x11c1c4000 + 70896996
6   QtWebEngineCore               	       0x122e74490 0x11c1c4000 + 113968272
7   QtWebEngineCore               	       0x120560ee0 0x11c1c4000 + 70897376
8   QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
9   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
10  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 13:: CompositorTileWorker1
0   libsystem_kernel.dylib        	       0x18828a6ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1882c8894 _pthread_cond_wait + 1204
2   QtWebEngineCore               	       0x120579ee0 0x11c1c4000 + 70999776
3   QtWebEngineCore               	       0x122535018 0x11c1c4000 + 104271896
4   QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
5   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
6   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 14:: ThreadPoolSingleThreadSharedForeground0
0   libsystem_kernel.dylib        	       0x188286f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x188299604 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18828faf8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x18828729c mach_msg + 24
4   QtWebEngineCore               	       0x1205949f4 0x11c1c4000 + 71109108
5   QtWebEngineCore               	       0x12051db64 0x11c1c4000 + 70622052
6   QtWebEngineCore               	       0x1205544d0 0x11c1c4000 + 70845648
7   QtWebEngineCore               	       0x120554e50 0x11c1c4000 + 70848080
8   QtWebEngineCore               	       0x120554bfc 0x11c1c4000 + 70847484
9   QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
10  libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
11  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 15:: NetworkConfigWatcher
0   libsystem_kernel.dylib        	       0x188286f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x188299604 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18828faf8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x18828729c mach_msg + 24
4   QtWebEngineCore               	       0x1205949f4 0x11c1c4000 + 71109108
5   QtWebEngineCore               	       0x12051db64 0x11c1c4000 + 70622052
6   QtWebEngineCore               	       0x12051dae0 0x11c1c4000 + 70621920
7   QtWebEngineCore               	       0x1204cc584 0x11c1c4000 + 70288772
8   QtWebEngineCore               	       0x12053e078 0x11c1c4000 + 70754424
9   QtWebEngineCore               	       0x1204fd5d0 0x11c1c4000 + 70489552
10  QtWebEngineCore               	       0x120560d64 0x11c1c4000 + 70896996
11  QtWebEngineCore               	       0x120560ee0 0x11c1c4000 + 70897376
12  QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
13  libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
14  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 16:: VizCompositorThread
0   libsystem_kernel.dylib        	       0x188286f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x188299604 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18828faf8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x18828729c mach_msg + 24
4   QtWebEngineCore               	       0x1205949f4 0x11c1c4000 + 71109108
5   QtWebEngineCore               	       0x12051db64 0x11c1c4000 + 70622052
6   QtWebEngineCore               	       0x1204cc520 0x11c1c4000 + 70288672
7   QtWebEngineCore               	       0x12053e078 0x11c1c4000 + 70754424
8   QtWebEngineCore               	       0x1204fd5d0 0x11c1c4000 + 70489552
9   QtWebEngineCore               	       0x120560d64 0x11c1c4000 + 70896996
10  QtWebEngineCore               	       0x120560ee0 0x11c1c4000 + 70897376
11  QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
12  libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
13  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 17:
0   libsystem_pthread.dylib       	       0x1882c30e8 start_wqthread + 0

Thread 18:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x188286f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x188299604 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18828faf8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x18828729c mach_msg + 24
4   CoreFoundation                	       0x1883b0a4c __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1883af2ac __CFRunLoopRun + 1212
6   CoreFoundation                	       0x1883ae734 CFRunLoopRunSpecific + 588
7   AppKit                        	       0x18c04b278 _NSEventThread + 148
8   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 19:: NetworkService
0   libsystem_kernel.dylib        	       0x188292cfc kevent64 + 8
1   QtWebEngineCore               	       0x12059adb4 0x11c1c4000 + 71134644
2   QtWebEngineCore               	       0x12059abac 0x11c1c4000 + 71134124
3   QtWebEngineCore               	       0x12053e078 0x11c1c4000 + 70754424
4   QtWebEngineCore               	       0x1204fd5d0 0x11c1c4000 + 70489552
5   QtWebEngineCore               	       0x120560d64 0x11c1c4000 + 70896996
6   QtWebEngineCore               	       0x120560ee0 0x11c1c4000 + 70897376
7   QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
8   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 20:: NetworkNotificationThreadMac
0   libsystem_kernel.dylib        	       0x188286f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x188299604 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18828faf8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x18828729c mach_msg + 24
4   CoreFoundation                	       0x1883b0a4c __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x1883af2ac __CFRunLoopRun + 1212
6   CoreFoundation                	       0x1883ae734 CFRunLoopRunSpecific + 588
7   Foundation                    	       0x18957f518 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8   QtWebEngineCore               	       0x1205cab50 0x11c1c4000 + 71330640
9   QtWebEngineCore               	       0x1205c94bc 0x11c1c4000 + 71324860
10  QtWebEngineCore               	       0x12053e078 0x11c1c4000 + 70754424
11  QtWebEngineCore               	       0x1204fd5d0 0x11c1c4000 + 70489552
12  QtWebEngineCore               	       0x120560d64 0x11c1c4000 + 70896996
13  QtWebEngineCore               	       0x120560ee0 0x11c1c4000 + 70897376
14  QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
15  libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
16  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 21:: NetworkConfigWatcher
0   libsystem_kernel.dylib        	       0x188286f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x188299604 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18828faf8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x18828729c mach_msg + 24
4   QtWebEngineCore               	       0x1205949f4 0x11c1c4000 + 71109108
5   QtWebEngineCore               	       0x12051db64 0x11c1c4000 + 70622052
6   QtWebEngineCore               	       0x12051dae0 0x11c1c4000 + 70621920
7   QtWebEngineCore               	       0x1204cc584 0x11c1c4000 + 70288772
8   QtWebEngineCore               	       0x12053e078 0x11c1c4000 + 70754424
9   QtWebEngineCore               	       0x1204fd5d0 0x11c1c4000 + 70489552
10  QtWebEngineCore               	       0x120560d64 0x11c1c4000 + 70896996
11  QtWebEngineCore               	       0x120560ee0 0x11c1c4000 + 70897376
12  QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
13  libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
14  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 22:: ThreadPoolBackgroundWorker
0   libsystem_kernel.dylib        	       0x188286f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x188299604 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18828faf8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x18828729c mach_msg + 24
4   QtWebEngineCore               	       0x1205949f4 0x11c1c4000 + 71109108
5   QtWebEngineCore               	       0x12051db64 0x11c1c4000 + 70622052
6   QtWebEngineCore               	       0x1205544d0 0x11c1c4000 + 70845648
7   QtWebEngineCore               	       0x120554e50 0x11c1c4000 + 70848080
8   QtWebEngineCore               	       0x120554bdc 0x11c1c4000 + 70847452
9   QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
10  libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
11  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 23:: ThreadPoolSingleThreadForegroundBlocking1
0   libsystem_kernel.dylib        	       0x188286f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x188299604 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18828faf8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x18828729c mach_msg + 24
4   QtWebEngineCore               	       0x1205949f4 0x11c1c4000 + 71109108
5   QtWebEngineCore               	       0x12051db64 0x11c1c4000 + 70622052
6   QtWebEngineCore               	       0x1205544d0 0x11c1c4000 + 70845648
7   QtWebEngineCore               	       0x12055526c 0x11c1c4000 + 70849132
8   QtWebEngineCore               	       0x120554bec 0x11c1c4000 + 70847468
9   QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
10  libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
11  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 24:: ThreadPoolForegroundWorker
0   libsystem_kernel.dylib        	       0x188286f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x188299604 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18828faf8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x18828729c mach_msg + 24
4   QtWebEngineCore               	       0x1205949f4 0x11c1c4000 + 71109108
5   QtWebEngineCore               	       0x12051db64 0x11c1c4000 + 70622052
6   QtWebEngineCore               	       0x1205544d0 0x11c1c4000 + 70845648
7   QtWebEngineCore               	       0x120554e50 0x11c1c4000 + 70848080
8   QtWebEngineCore               	       0x120554ba8 0x11c1c4000 + 70847400
9   QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
10  libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
11  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 25:: MemoryInfra
0   libsystem_kernel.dylib        	       0x188286f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x188299604 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18828faf8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x18828729c mach_msg + 24
4   QtWebEngineCore               	       0x1205949f4 0x11c1c4000 + 71109108
5   QtWebEngineCore               	       0x12051db64 0x11c1c4000 + 70622052
6   QtWebEngineCore               	       0x12051dae0 0x11c1c4000 + 70621920
7   QtWebEngineCore               	       0x1204cc584 0x11c1c4000 + 70288772
8   QtWebEngineCore               	       0x12053e078 0x11c1c4000 + 70754424
9   QtWebEngineCore               	       0x1204fd5d0 0x11c1c4000 + 70489552
10  QtWebEngineCore               	       0x120560d64 0x11c1c4000 + 70896996
11  QtWebEngineCore               	       0x120560ee0 0x11c1c4000 + 70897376
12  QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
13  libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
14  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 26:: ThreadPoolSingleThreadSharedBackgroundBlocking2
0   libsystem_kernel.dylib        	       0x188286f54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x188299604 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x18828faf8 mach_msg_overwrite + 480
3   libsystem_kernel.dylib        	       0x18828729c mach_msg + 24
4   QtWebEngineCore               	       0x1205949f4 0x11c1c4000 + 71109108
5   QtWebEngineCore               	       0x12051db64 0x11c1c4000 + 70622052
6   QtWebEngineCore               	       0x1205544d0 0x11c1c4000 + 70845648
7   QtWebEngineCore               	       0x120554e50 0x11c1c4000 + 70848080
8   QtWebEngineCore               	       0x120554c1c 0x11c1c4000 + 70847516
9   QtWebEngineCore               	       0x12057a9e4 0x11c1c4000 + 71002596
10  libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
11  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 27:: QNetworkAccessManager thread
0   libsystem_kernel.dylib        	       0x18828f830 poll + 8
1   QtCore                        	       0x1081461d0 qt_safe_poll(pollfd*, unsigned int, QDeadlineTimer) + 180
2   QtCore                        	       0x10814a6a4 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 904
3   QtCore                        	       0x107fddabc QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 540
4   QtCore                        	       0x1080b81cc QThread::exec() + 284
5   QtCore                        	       0x1081483ec 0x107f50000 + 2065388
6   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 28:: QNetworkAccessManager thread
0   libsystem_kernel.dylib        	       0x18828f830 poll + 8
1   QtCore                        	       0x108146158 qt_safe_poll(pollfd*, unsigned int, QDeadlineTimer) + 60
2   QtCore                        	       0x10814a6a4 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 904
3   QtCore                        	       0x107fddabc QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 540
4   QtCore                        	       0x1080b81cc QThread::exec() + 284
5   QtCore                        	       0x1081483ec 0x107f50000 + 2065388
6   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 29:
0   libsystem_pthread.dylib       	       0x1882c30e8 start_wqthread + 0

Thread 30:
0   libsystem_pthread.dylib       	       0x1882c30e8 start_wqthread + 0

Thread 31:
0   libsystem_pthread.dylib       	       0x1882c30e8 start_wqthread + 0

Thread 32:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18828a6ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1882c8894 _pthread_cond_wait + 1204
2   QtCore                        	       0x1081558d8 0x107f50000 + 2119896
3   QtCore                        	       0x10815578c QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x10814ffb0 0x107f50000 + 2097072
5   QtCore                        	       0x1081483ec 0x107f50000 + 2065388
6   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 33:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18828a6ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1882c8894 _pthread_cond_wait + 1204
2   QtCore                        	       0x1081558d8 0x107f50000 + 2119896
3   QtCore                        	       0x10815578c QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x10814ffb0 0x107f50000 + 2097072
5   QtCore                        	       0x1081483ec 0x107f50000 + 2065388
6   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 34:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18828a6ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1882c8894 _pthread_cond_wait + 1204
2   QtCore                        	       0x1081558d8 0x107f50000 + 2119896
3   QtCore                        	       0x10815578c QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x10814ffb0 0x107f50000 + 2097072
5   QtCore                        	       0x1081483ec 0x107f50000 + 2065388
6   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 35:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18828a6ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1882c8894 _pthread_cond_wait + 1204
2   QtCore                        	       0x1081558d8 0x107f50000 + 2119896
3   QtCore                        	       0x10815578c QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x10814ffb0 0x107f50000 + 2097072
5   QtCore                        	       0x1081483ec 0x107f50000 + 2065388
6   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 36 Crashed:: Thread (pooled)
0   libqwebp.dylib                	       0x10ecfa258 0x10ecb8000 + 270936
1   libqwebp.dylib                	       0x10ece6e64 0x10ecb8000 + 192100
2   libqwebp.dylib                	       0x10ecfe7c0 WebPEncode + 1396
3   libqwebp.dylib                	       0x10ecbdd94 0x10ecb8000 + 23956
4   QtGui                         	       0x106238160 QImageWriter::write(QImage const&) + 772
5   QtGui                         	       0x10621b8b8 QImage::save(QIODevice*, char const*, int) const + 152
6   GoldenDict-ng                 	       0x1048514ac GdTiff::tiff2img(std::__1::vector<char, std::__1::allocator<char>>&) + 160
7   GoldenDict-ng                 	       0x1047863b4 Mdx::MddResourceRequest::run() + 968
8   GoldenDict-ng                 	       0x1046b4764 0x104678000 + 247652
9   QtCore                        	       0x10814fda4 0x107f50000 + 2096548
10  QtCore                        	       0x1081483ec 0x107f50000 + 2065388
11  libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
12  libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 37:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18828a6ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1882c8894 _pthread_cond_wait + 1204
2   QtCore                        	       0x1081558d8 0x107f50000 + 2119896
3   QtCore                        	       0x10815578c QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x10814ffb0 0x107f50000 + 2097072
5   QtCore                        	       0x1081483ec 0x107f50000 + 2065388
6   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 38:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18828a6ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1882c8894 _pthread_cond_wait + 1204
2   QtCore                        	       0x1081558d8 0x107f50000 + 2119896
3   QtCore                        	       0x10815578c QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x10814ffb0 0x107f50000 + 2097072
5   QtCore                        	       0x1081483ec 0x107f50000 + 2065388
6   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 39:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18828a6ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1882c8894 _pthread_cond_wait + 1204
2   QtCore                        	       0x1081558d8 0x107f50000 + 2119896
3   QtCore                        	       0x10815578c QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x10814ffb0 0x107f50000 + 2097072
5   QtCore                        	       0x1081483ec 0x107f50000 + 2065388
6   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 40:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18828a6ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1882c8894 _pthread_cond_wait + 1204
2   QtCore                        	       0x1081558d8 0x107f50000 + 2119896
3   QtCore                        	       0x10815578c QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x10814ffb0 0x107f50000 + 2097072
5   QtCore                        	       0x1081483ec 0x107f50000 + 2065388
6   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 41:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18828a6ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1882c8894 _pthread_cond_wait + 1204
2   QtCore                        	       0x1081558d8 0x107f50000 + 2119896
3   QtCore                        	       0x10815578c QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x10814ffb0 0x107f50000 + 2097072
5   QtCore                        	       0x1081483ec 0x107f50000 + 2065388
6   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 42:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18828a6ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1882c8894 _pthread_cond_wait + 1204
2   QtCore                        	       0x1081558d8 0x107f50000 + 2119896
3   QtCore                        	       0x10815578c QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x10814ffb0 0x107f50000 + 2097072
5   QtCore                        	       0x1081483ec 0x107f50000 + 2065388
6   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 43:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18828a6ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1882c8894 _pthread_cond_wait + 1204
2   QtCore                        	       0x1081558d8 0x107f50000 + 2119896
3   QtCore                        	       0x10815578c QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x10814ffb0 0x107f50000 + 2097072
5   QtCore                        	       0x1081483ec 0x107f50000 + 2065388
6   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 44:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18828a6ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1882c8894 _pthread_cond_wait + 1204
2   QtCore                        	       0x1081558d8 0x107f50000 + 2119896
3   QtCore                        	       0x10815578c QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x10814ffb0 0x107f50000 + 2097072
5   QtCore                        	       0x1081483ec 0x107f50000 + 2065388
6   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 45:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18828a6ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1882c8894 _pthread_cond_wait + 1204
2   QtCore                        	       0x1081558d8 0x107f50000 + 2119896
3   QtCore                        	       0x10815578c QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x10814ffb0 0x107f50000 + 2097072
5   QtCore                        	       0x1081483ec 0x107f50000 + 2065388
6   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 46:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18828a6ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1882c8894 _pthread_cond_wait + 1204
2   QtCore                        	       0x1081558d8 0x107f50000 + 2119896
3   QtCore                        	       0x10815578c QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x10814ffb0 0x107f50000 + 2097072
5   QtCore                        	       0x1081483ec 0x107f50000 + 2065388
6   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 47:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18828a6ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1882c8894 _pthread_cond_wait + 1204
2   QtCore                        	       0x1081558d8 0x107f50000 + 2119896
3   QtCore                        	       0x10815578c QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x10814ffb0 0x107f50000 + 2097072
5   QtCore                        	       0x1081483ec 0x107f50000 + 2065388
6   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 48:: Thread (pooled)
0   libsystem_kernel.dylib        	       0x18828a6ec __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x1882c8894 _pthread_cond_wait + 1204
2   QtCore                        	       0x1081558d8 0x107f50000 + 2119896
3   QtCore                        	       0x10815578c QWaitCondition::wait(QMutex*, QDeadlineTimer) + 108
4   QtCore                        	       0x10814ffb0 0x107f50000 + 2097072
5   QtCore                        	       0x1081483ec 0x107f50000 + 2065388
6   libsystem_pthread.dylib       	       0x1882c82e4 _pthread_start + 136
7   libsystem_pthread.dylib       	       0x1882c30fc thread_start + 8

Thread 36 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x000000000000006d   x3: 0x0000000000000048
    x4: 0x0000000104dec900   x5: 0x0000000000000000   x6: 0x0000000000000048   x7: 0x0000000000003fff
    x8: 0x0000000062de5ffc   x9: 0x0000000000000001  x10: 0x000000007bfc0000  x11: 0x0000000006128000
   x12: 0x0000000000000651  x13: 0x0000000138000028  x14: 0x00000000ffff8048  x15: 0x000000000000060a
   x16: 0x00000000ffff7fff  x17: 0x00000001fa27a898  x18: 0x0000000000000000  x19: 0x00000001103301f0
   x20: 0x0000000000000001  x21: 0x0000000110330e24  x22: 0x0000000110330070  x23: 0x0000000129c10000
   x24: 0x0000000129cd0000  x25: 0x0000000000000000  x26: 0x0000000129c10006  x27: 0x0000000062de5ffb
   x28: 0x0000000172561608   fp: 0x0000000172561510   lr: 0x000000010ecfa248
    sp: 0x00000001725614c0   pc: 0x000000010ecfa258 cpsr: 0x20001000
   far: 0x00000001ef7dbffe  esr: 0x92000007 (Data Abort) byte read Translation fault

### PR DESCRIPTION
**Pull request by xiaoyifang**
fix #2202

### CODE REVIEW

File: src/tiff.cc [hunk 1]
```diff
@@ -8,23 +8,22 @@
...
+    QBuffer buffer( &ba );
     buffer.open( QIODevice::WriteOnly );
-
     QSize screenSize = QApplication::primaryScreen()->availableSize();
     QSize imgSize    = img.size();
     int scaleSize    = qMin( imgSize.width(), screenSize.width() );
-    img.scaledToWidth( scaleSize ).save( &buffer, "webp" );
 
-    memcpy( data.data(), ba.data(), ba.size() );
-    data.resize( ba.size() );
```
Comment (shenlebantongying) [inline src/tiff.cc:27]: Don't revert anything else except swap the order of those 2 lines.

QBuffer control the content of the `QByteArray ba`. The original code involves an implicit conversion `QByteaArray->char*`.

Also, `&std::vector::front` is a crash if the vector is empty. It generally shouldn't occur in post-c++11 code.

**Comment by shenlebantongying** [comment]
Thanks.
