### PR TITLE
fix:use a different socketname

### LINKED ISSUE #599: can not start immediately after quit old goldendict
**Describe the bug**

After quit the offical gd version ,this repo's goldendict can not start and will crash when starting.

**To Reproduce**
- start the official version of gd ,version 
image
- when the fulltext creation is beginning , quit the gd.
- the webengine goldendict of this repo can not start and will crash

**Desktop (please complete the following information):**
 - OS: Windows
 - latest version

**Additional context**
Maybe related with singleapplication strategy.

### PR DESCRIPTION
**Pull request by xiaoyifang**
fix #599

### CODE REVIEW

File: thirdparty/qtsingleapplication/src/qtlocalpeer.cpp [hunk 1]
```diff
@@ -62,46 +62,30 @@ const char* QtLocalPeer::ack = "ack";
...
-#endif
-
     server = new QLocalServer(this);
     QString lockName = QDir(QDir::tempPath()).absolutePath()
                        + QLatin1Char('/') + socketName
                        + QLatin1String("-gdlockfile");
     lockFile = new QLockFile(lockName);
     lockFile->setStaleLockTime(0);
     if ( !lockFile->tryLock( 0 ) ) {
-        if ( lockFile->error() != QLockFile::NoError && lockFile->error() != QLockFile::LockFailedError ) {
```
Comment (shenlebantongying) [inline thirdparty/qtsingleapplication/src/qtlocalpeer.cpp:102]: The `QLockFile::LockFailedError` happens when `someone else already locked it".

It happens when starting a new instance.

We want this "error" to happen so that we know there is already an instance running.

So it should not print a warning, LockFailedError should not print a warning.

This part should not be changed

Comment (xiaoyifang) [reply thirdparty/qtsingleapplication/src/qtlocalpeer.cpp:102]: when lock failed ,print the reason.  users who check the log file can determine at that time.   
It will give users a clear viewpoint and choice.

And consider it was only a log,  print  a little much more is ok.

Comment (shenlebantongying) [reply thirdparty/qtsingleapplication/src/qtlocalpeer.cpp:102]: It will print when searching a word via command line when nothing wrong happens:

image

Comment (xiaoyifang) [reply thirdparty/qtsingleapplication/src/qtlocalpeer.cpp]: done

Comment (xiaoyifang) [reply thirdparty/qtsingleapplication/src/qtlocalpeer.cpp]: And about the indentation .   the clang-format seems does not take effect in the first `if`.

**Comment by shenlebantongying** [comment]
The code looks ok to me.

Is this a QtSingleApplication bug where the socket resuing may fail?

**Comment by xiaoyifang** [comment]
> The changes looks ok to me.
> 
> Is this a QtSingleApplication bug where the socket resuing may fail?

I guess when the old goldendict quit ,the socket failed to close which makes the goldendict-ng can not start.

**Comment by shenlebantongying** [comment]
In both old & new code, only the lock files' status is checked to know if an instance is already running.

https://github.com/goldendict/goldendict/blob/192f0d9f25350c42ff7c536d49fefdc429202607/qtsingleapplication/src/qtlocalpeer.cpp#L113-L133

And old & new GD are using different lockfile, they shouldn't conflict.

I think if the socket has problems, then the messages should be affected rather than starting up. Even if the socket has problems, the secondary instance should start without a problem?

I cannot reproduce the https://github.com/xiaoyifang/goldendict-ng/issues/599, so i am not sure, but if this solves the problems, this should be OK to merge.
