### PR TITLE
fix:favorite headword retrieve logic

### LINKED ISSUE #1484: KDE adds "&" in group name and article tabs names (history and favorites)
**Describe the bug**
GoldenDict keep adding "&" character in group name

**To Reproduce**
1. Go to Edit
2. Click on Dictionaries
3. Click on Groups
4. Click on OK | Apply button
5. See error

**Screenshots**
Screenshot_20240428_115805

**OS and software versions**
KDE Plasma 6.0.4
Goldendict-ng 24.02.16.e78aff27 at 2024-04-24T04:58:00Z
Qt 6.7.0 GCC 13.2.1 20230801 arch linux 6.8.7-arch1-2 x86_64-little_endian-lp64
Flags: MAKE_ZIM_SUPPORT USE_ICONV MAKE_CHINESE_CONVERSION_SUPPORT

### PR DESCRIPTION
**Pull request by xiaoyifang**
fix #1484

### CODE REVIEW

**Comment by shenlebantongying** [comment]
I will check this out when I am near my linux box again within two days :)

File: src/ui/mainwindow.cc [hunk 1]
```diff
@@ -4399,15 +4408,22 @@ void MainWindow::addAllTabsToFavorites()
   }
 
   for ( int i = 0; i < ui.tabWidget->count(); i++ ) {
-    QString headword = ui.tabWidget->tabText( i );
-    ui.favoritesPaneWidget->addHeadword( folder, unescapeTabHeader( headword ) );
+    auto view = dynamic_cast< ArticleView * >( ui.tabWidget->widget( i ) );
```
Comment (shenlebantongying) [inline src/ui/mainwindow.cc:4411]:
```suggestion
    auto view = qobject_cast< ArticleView * >( ui.tabWidget->widget( i ) );
```
