### PR TITLE
fix: cjk expand character can not be searched

### LINKED ISSUE #2011: Why isn’t Chinese characters with expanded I supported?
image
我确认我的词典里有
image

### PR DESCRIPTION
**Pull request by xiaoyifang**
fix #2011

### CODE REVIEW

File: src/common/folding.cc [hunk 1]
```diff
@@ -156,7 +156,7 @@ std::u32string applyWhitespaceAndPunctOnly( std::u32string const & in )
 bool isWhitespace( char32_t ch )
 {
   //invisible character should be treated as whitespace as well.
```
Comment (xiaoyifang) [inline src/common/folding.cc:158]:
```suggestion

```

File: src/common/globalregex.hh [hunk 2]
```diff
@@ -72,7 +72,7 @@ const static QRegularExpression accentMark( R"(\p{M})", QRegularExpression::UseU
 const static QRegularExpression markPuncSpace( R"([\p{M}\p{Z}\p{C}\p{P}])",
                                                QRegularExpression::UseUnicodePropertiesOption );
 //contain unicode space and mark.invisible
```
Comment (xiaoyifang) [inline src/common/globalregex.hh:74]:
```suggestion
//contain unicode space and mark.
```
