### PR TITLE
Revert "fix: multimedia memleak "

### LINKED ISSUE #2210: Program sometimes plays the audio of the previous searched word.
I have enabled **Auto-pronounce words in main window**, but program sometimes plays the audio of the previous searched  word, sometimes it first plays previous word before playing the current one. This seems to happen randomly.

Version: 25.04.0.7f9a23f at 2025-02-19T06:18:38Z
Qt 6.7.2 MSVC 194234436
windows winnt 10.0.26100 x86_64-little_endian-llp64
Flags: ZIM EPWING OPENCC

### PR DESCRIPTION
**Pull request by xiaoyifang**
This reverts commit f8966785a1c3c252bb5823a019d4c05a2fe216db.

fix #2210

### CODE REVIEW

File: src/audio/multimediaaudioplayer.hh [hunk 1]
```diff
@@ -27,7 +28,7 @@ private slots:
 
 
 private:
-  QBuffer audioBuffer;
+  QPointer< QBuffer > audioBuffer;
```
Comment (shenlebantongying) [inline src/audio/multimediaaudioplayer.hh:31]: Change this to std::unique_ptr/QScopedPointer instead?

QPointer doesn't manage lifetime but QScopedPointer does.

There is a small leak here.

**Comment by xiaoyifang** [comment]
I'll fix it in another PR.

shenleban tongying ***@***.***> 于2025年3月5日周三 22:10写道：
