### PR TITLE
fix: shortcut navigation through dictionary and page

### LINKED ISSUE #1005: from community: alt+down does not work expectedly
**Describe the bug**

> There is one annoying bug that I wish the developer would sort out in the future. It has to do with the use of the keyboard shortcut Alt + Down/Up to navigate between the dictionaries within a group. So, I have ten dictionaries in the group, and say I left off reading the dictionary content for the search word at dictionary number 5 - on my next search the results will start from the first dictionary in the group, but the next dictionary I get to read upon pressing Alt + Down will be dictionary number 6, instead of dictionary number 2.
> Curiously, one can get around this problem if the result navigation pane is turned on, in which case Alt + Down navigation will follow the normal dictionary order from the first dictionary to second, third and so on. As I don’t want any panels on my screen, I’d like to be able to do the same without showing the result navigation pane.
> 
> One other thing that I’d like to see sorted out in the future version is the problem with the focus after hitting Enter to search for the word. I reported this bug before, and the developer kindly answered my request and the issue was partly resolved in the following versions. Up and down keys are now functional after pressing Enter, and I can browse the results without taking my hands off the keyboard. However, I still can’t go down the page using Page Down or Space button, without previously clicking somewhere on the page to regain the focus.

### PR DESCRIPTION
**Pull request by xiaoyifang**
fix #1005

### CODE REVIEW

File: src/ui/mainwindow.cc [hunk 1]
```diff
@@ -1,6 +1,7 @@
 /* This file is (c) 2008-2012 Konstantin Isakov <ikm@goldendict.org>
  * Part of GoldenDict. Licensed under GPLv3 or later, see the LICENSE file */
 
+#include "qnamespace.h"
```
Comment (shenlebantongying) [inline src/ui/mainwindow.cc:4]:
```suggestion
#include <Qt>
```

**Review by shenlebantongying — CHANGES_REQUESTED** [review]

**Comment by shenlebantongying** [comment]
I just discovered that suggested changes can be directly committed in 1 click :smile:
